# Generated by Django 5.0.7 on 2024-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_task2'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='anotado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='diasanotados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='tiex',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
    ]
