# Generated by Django 5.0.7 on 2024-08-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_task_anotado_task_diasanotados_task_tiex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datecontra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
